"use client";
import {useEffect,useState} from "react";
import {ArrowRight,Volume2} from "lucide-react";
import {Checkbox} from "@/components/ui/checkbox";
import {VoiceInput} from "@/components/voice-input";
import {containsSensitive,MODEL_URL,REVISION,type Journey,type Answer} from "@/lib/safety";
import {saveTrial,type Trial} from "@/lib/evaluation";
const topics={before:["Someone sent a link asking for my banking code.","An online seller wants payment before delivery.","An investment promises to double my money."],after:["I already paid and suspect a scam.","My bank complaint remains unresolved."],learn:["How do I protect my banking codes?","How can I recognise an investment scam?","How do I check an online seller?"]};
export function JourneyPanel({journey}:{journey:Journey}){
 const [question,setQuestion]=useState(""),[answer,setAnswer]=useState<Answer|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[asrModel,setAsrModel]=useState(""),[confirmed,setConfirmed]=useState(false),[testing,setTesting]=useState(false),[trial,setTrial]=useState<Trial|null>(null),[saved,setSaved]=useState(false),[quiz,setQuiz]=useState<boolean|null>(null),[canSpeak,setCanSpeak]=useState(false);
 useEffect(()=>{setCanSpeak("speechSynthesis" in window);return()=>{window.speechSynthesis?.cancel();};},[]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!context)return;const controller=new AbortController();
 try{context.registerTool({name:"stage_safety_question",description:"Stage a non-sensitive safety question in the visible form for the user to review. Does not submit or record data.",inputSchema:{type:"object",properties:{question:{type:"string",maxLength:600}},required:["question"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{const q=(input as {question?:unknown})?.question;if(typeof q!=="string"||!q.trim()||q.length>600||containsSensitive(q))throw new Error("Use a short situation without private details.");setQuestion(q);setAnswer(null);setAsrModel("");setConfirmed(false);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return {staged:true,submitted:false};}},{signal:controller.signal});}catch{}return()=>controller.abort();},[]);
 function edit(value:string){setQuestion(value);setAnswer(null);setTrial(null);setSaved(false);setConfirmed(false);}
 async function ask(){
  setError("");setAnswer(null);setTrial(null);setSaved(false);
  if(!question.trim()){setError("Describe a situation or choose a topic.");return;}
  if(containsSensitive(question)){setQuestion("");setAsrModel("");setError("Private details or numbers were detected and cleared. Please describe only the situation.");return;}
  if(asrModel&&!confirmed){setError("Please check and confirm the transcript first.");return;}
  setBusy(true);const start=performance.now();
  try{const response=await fetch("/api/answer",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question,journey}),signal:AbortSignal.timeout(12000)});const data=await response.json() as Answer;if(!data.status)throw new Error("Guidance is unavailable. Pause and contact your bank through a trusted channel.");setAnswer(data);const t:Trial={kind:"answer",journey,outcome:data.status==="ok"?"ok":data.status==="no_match"?"no_match":"failed",latencyMs:Math.round(performance.now()-start)};setTrial(t);if(testing&&data.status!=="ok"){if(saveTrial(t))setSaved(true);else setError("The local test result could not be saved.");}}
  catch(e){setError(e instanceof Error?e.message:"Guidance is unavailable.");if(testing)saveTrial({kind:"answer",journey,outcome:"failed",latencyMs:Math.min(120000,Math.round(performance.now()-start))});}
  finally{setBusy(false);}
 }
 function rate(helpful?:boolean){if(!testing||!trial||saved)return;const ok=saveTrial({...trial,...(helpful===undefined?{}:{helpful})});setSaved(ok);if(!ok)setError("The local test result could not be saved.");}
 function listen(){if(!answer)return;window.speechSynthesis.cancel();const speech=new SpeechSynthesisUtterance(answer.cards.flatMap(c=>[c.title,...c.steps]).join(". "));speech.lang="en-NG";speech.rate=.9;window.speechSynthesis.speak(speech);}
 return <div className="card-body"><span className="step-label">01 / {journey==="learn"?"LEARN A SAFER HABIT":"TELL US WHAT’S HAPPENING"}</span><h2>{journey==="after"?"Let’s take the next safe step.":journey==="learn"?"Build your scam-spotting skills.":"Let’s check before you send."}</h2><p>No names, account numbers, PINs, passwords or OTPs. Just describe the situation.</p>
 {journey==="after"&&<div className="notice">Suspect fraud? Contact your bank now using its official app, website or a trusted contact. Do not wait for this tool. <a href="https://www.cbn.gov.ng/supervision/cpdfraudandscam.html" target="_blank" rel="noreferrer">CBN guidance</a></div>}
 <VoiceInput journey={journey} testing={testing} onTranscript={(text,model)=>{edit(text);setAsrModel(model);}}/>
 <div className="divider"><span>or use your keyboard</span></div><label htmlFor={"question-"+journey}>{asrModel?"Check and correct what we heard":"What would you like to check?"}</label><textarea id={"question-"+journey} value={question} maxLength={600} autoComplete="off" spellCheck={false} disabled={busy} onChange={e=>edit(e.target.value)} placeholder="For example: A caller asks for my banking code."/>
 {asrModel&&<><p className="microcopy">Transcribed by <a href={MODEL_URL}>{asrModel}</a> · {REVISION.slice(0,8)}. Corrections are yours. Confidence is not supplied by this model.</p><label className="consent"><Checkbox checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/>I checked the transcript. It describes my situation and has no private details.</label></>}
 <button className="primary" disabled={busy||!!asrModel&&!confirmed} onClick={ask}>{busy?"Checking source-backed guidance…":"Check my next step"}<ArrowRight size={18}/></button>
 <div className="chips" aria-label="Suggested safety questions">{topics[journey].map((t,i)=><button disabled={busy} key={t} onClick={()=>{edit(t);setAsrModel("");}}>{["Try: "+(journey==="after"?"Suspected fraud":journey==="learn"?"Banking codes":"Suspicious link"),journey==="after"?"Unresolved complaint":journey==="learn"?"Investment warning":"Online seller",journey==="learn"?"Online seller":"Investment offer"][i]}</button>)}</div>
 <label className="consent"><Checkbox checked={testing} disabled={busy} onCheckedChange={v=>{setTesting(v===true);setTrial(null);}}/>Optional: save anonymous test measurements on this device only. No text or audio. Turning this off stops new records. <a href="/evaluation">View or delete records</a>.</label>
 {error&&<div role="alert" className="notice">{error}</div>}
 {answer&&<section className="result" aria-live="polite"><span className="step-label">02 / YOUR NEXT SAFE STEP</span><p>{answer.message}</p>{answer.cards.map(c=><article key={c.id}><h3>{c.title}</h3><ol>{c.steps.map(s=><li key={s}>{s}</li>)}</ol><div className="provenance"><a href={c.source} target="_blank" rel="noreferrer">{c.sourceTitle} ↗</a><br/>{c.section}<br/>Checked {c.checked} · Review due {c.expires}<br/>{c.review}</div></article>)}<p className="microcopy">Answer engine: {answer.engine}. Answer model: none.<br/>Speech model used: {asrModel||"none — typed input"}. Library {answer.kbVersion}.</p>{answer.cards.length>0&&<><button className="secondary" onClick={listen} disabled={!canSpeak}><Volume2 size={16}/> Read guidance aloud</button><p className="microcopy">Playback uses your browser’s voice service, not N-ATLaS. Only public guidance is spoken.</p></>}
 {testing&&trial&&!saved&&answer.status==="ok"&&<div className="content-panel"><p>Was this guidance useful? Save this test:</p><div className="chips"><button onClick={()=>rate(true)}>Yes</button><button onClick={()=>rate(false)}>No</button><button onClick={()=>rate()}>Save without rating</button></div></div>}{saved&&<p role="status" className="microcopy">Measurement saved on this device. No question or transcript saved.</p>}
 {journey==="learn"&&answer.cards.length>0&&<div className="content-panel"><h3>One quick practice</h3><p>A caller says your account will be blocked unless you share a code. What is the safer next step?</p><div className="chips"><button onClick={()=>{setQuiz(true);if(testing)saveTrial({kind:"quiz",journey,outcome:"ok",latencyMs:0});}}>End the call and contact my bank independently</button><button onClick={()=>{setQuiz(false);if(testing)saveTrial({kind:"quiz",journey,outcome:"failed",latencyMs:0});}}>Share the code to avoid the block</button></div>{quiz!==null&&<p role="status">{quiz?"Yes. Keep the code private and independently verify the caller.":"Keep the code private. Contact the bank independently instead."} <a href="https://www.cbn.gov.ng/FinInc/FinLit/BillOfRights.html">CBN source</a>. Static practice feedback; no model used.</p>}</div>}</section>}
 </div>;
}


