import { CARDS, containsSensitive, currentSourceCards, type Answer, type Card } from "./safety.ts";
import { hasContactedBank } from "./payment-context.ts";

export type FollowUp = { question: string; choices: { label: string; statement: string }[] };
export type Guidance = {
  sourceId: string;
  title: string;
  summary: string;
  steps: { text: string; why?: string }[];
  details: { title: string; text: string }[];
  followUp?: FollowUp;
};
// Reviewed scenario wording, selected from user-stated circumstances. No model
// prose, identifiers, amount/date values or quoted messages are copied here.
export function contextualGuidance(question: string, answer: Answer, now = new Date()): Guidance | null {
  if (answer.status !== "ok" || answer.bankInfo || containsSensitive(question) || question.length > 600) return null;
  const card = answer.cards.length === 1 ? answer.cards[0] : null;
  const trusted = card && currentSourceCards(CARDS, now).find(c => c.id === card.id);
  if (!trusted || !card || ["title", "steps", "why", "source", "checked", "expires"].some(k => JSON.stringify(card[k as keyof Card]) !== JSON.stringify(trusted[k as keyof Card]))) return null;
  const text = question.toLowerCase().replace(/[’']/g, "'");
  const pressure = !/\b(?:not urgent|no pressure|not rushing)\b/.test(text) && (/\b(?:rushing|rush|urgent|urgently|deadline|pressure)\b/.test(text) || /\b(?:wants?|demands?|insists?)\b.{0,45}\b(?:today|immediately)\b/.test(text));
  const alreadyContacted = hasContactedBank(question);
  const steps = trusted.steps.map((step, i) => ({ text: step, ...(trusted.why?.[i] ? { why: trusted.why[i] } : {}) }));
  const base = { sourceId: card.id, title: card.title, steps, details: [] };
  switch (card.id) {
    case "supplier": {
      const confirmed = /\bi (?:have )?(?:independently confirmed|confirmed (?:the change )?using (?:an? )?(?:old|existing|previous) contact)\b/.test(text);
      return { ...base, title: confirmed ? "Keep the change and your confirmation together" : "Confirm the changed details before paying",
        ...(confirmed ? {steps:[{text:"If the instruction differs from the change you confirmed, keep payment on hold."},{text:"If you still have a concern, resolve it through the supplier contact you already knew before paying.",why:"A successful callback is not an account-authentication service."}]} : {}),
        summary: confirmed ? "You said you confirmed through an existing contact. That is useful context, but it does not authenticate the receiving account." : "The issue is the changed payment instruction. A familiar supplier name or a reply in the same message does not independently confirm it.",
        details: [{title: "What to ask on the callback", text: "Ask whether the supplier changed the payment instructions and who authorised the change. Use a contact you had before this request. If there is a disagreement or you cannot reach that contact, keep the payment on hold."}, ...(pressure ? [{title:"About the deadline",text:"The time pressure you mentioned does not replace independent confirmation. Verify the change before acting on the deadline."}] : [])],
        ...(!confirmed ? {followUp:{question:"Have you confirmed the change through a contact you already had?",choices:[{label:"Not yet",statement:"I have not independently confirmed the change."},{label:"Yes, using an existing contact",statement:"I independently confirmed the change using an existing contact."}]}} : {}),
      };
    }
    case "school": return { ...base, title:"Check the fee instruction with the school itself", summary:"Your question concerns school payment instructions. PauseAm cannot check the school's receiving account, so the useful check is its own official payment process.", details:[{title:"What to confirm",text:"Ask the official school office or portal whether the instruction came from it and what payment route it currently requires. A forwarded screenshot or the sender's own link is not an independent check."}] };
    case "receipt": return { ...base, title:"Check your own account before releasing the goods", summary:"The receipt or alert you described is a claim of payment. PauseAm cannot establish whether your account received that payment.", details:[{title:"If the payment is missing",text:"Use your own bank's official service to check the transaction. Ask the bank to investigate any uncertainty; another receipt from the buyer does not resolve it."}] };
    case "shopping": return { ...base, title:"Check this seller before committing money", summary:"Your question is about buying from a seller. Independent evidence about that seller matters more than an attractive offer or a secure-looking page.", details:[{title:"Look for evidence you can check yourself",text:"Check independent reviews and the seller's established presence. An offer or review supplied only by the seller is not an independent check. If you have paid and the seller has disappeared, say that so we can help with reporting instead."}, ...(pressure ? [{title:"If you are being rushed",text:"Hold off while you check. Urgency does not establish the seller's identity or whether goods will arrive."}] : [])] };
    case "investment": return { ...base, title:"Examine the promised returns before investing", summary:"The concern is an investment promise. High returns described as quick, guaranteed or low risk need independent checking; PauseAm cannot verify the operator or predict returns.", details:[{title:"What would help you decide",text:"Research the investment independently and ask a qualified adviser about the risks before committing money. A payment receipt, testimonial or promised payout is not proof of future returns."}] };
    case "report": return { ...base, title: alreadyContacted ? "Follow up on the report you have already made" : "Report the payment concern to your bank now", summary:alreadyContacted ? "You said you have already contacted the bank. Keep its reference and response; if account access is still at risk, contact it urgently again." : "You described a payment or account concern that needs prompt attention. Your bank can investigate its records; PauseAm cannot establish who committed fraud or recover the money.", details:[{title:"Describe what happened, without guessing",text:"Through the bank's verified channel, explain the payment and what happened afterwards. Keep the confirmation and relevant messages privately. Ask for a complaint reference, what it will investigate and when to expect a response."},{title:"If access is also affected",text:"Tell the bank immediately. Change compromised passwords through the official service and enable two-factor authentication. Recovery is not guaranteed."}] };
    case "secrets": return { ...base, title:"Keep the requested banking code private", summary:"Your question mentions a PIN, OTP or banking password. You do not need to tell PauseAm the code or repeat it to a caller.", details:[{title:"If you have already shared it",text:"Contact your bank through its official service promptly and explain that banking information may be compromised. Do not share the code again. Ask the bank how to secure the affected access."},{title:"If you have not shared it",text:"End the request and verify it with the organisation independently. A caller's identity claim or pressure does not justify disclosing a banking secret."}] };
    case "mistaken": return { ...base, title:"Ask your bank to investigate the mistaken transfer", summary:"You described a possible transfer to the wrong recipient. An error needs investigation; it does not by itself establish that the recipient is a scammer.", details:[{title:"What to give the bank privately",text:"Keep the transfer confirmation. Provide the amount, date and reference only through the bank's verified complaint channel, then ask for a complaint reference and the next step. PauseAm cannot reverse the transfer or promise its recovery."}] };
    case "complaint": {
      const missing = /\b(?:not|never|hasn't|haven't|didn't|did not)\b.{0,30}\b(?:arrived|arrive|received|receive|credited|gone through)\b/.test(text);
      const deduction = /\b(?:debited|deducted|charged|deduction)\b/.test(text);
      return { ...base, title:alreadyContacted ? "Follow up on your existing bank complaint" : missing && deduction ? "Ask the bank to trace the payment you were debited for" : missing ? "Ask the bank to trace the missing transfer" : deduction ? "Ask the bank to explain the deduction" : "Get your payment issue recorded by the bank", summary:alreadyContacted ? "You said a complaint is already with the bank. You should not have to start the explanation from scratch: use its existing reference and keep its responses." : "A delayed payment or deduction needs the bank's transaction records. It is not enough for PauseAm to label it a scam or promise a reversal.",
        ...(alreadyContacted ? {steps:[{text:"Use the existing complaint reference to follow up through your bank's official complaints channel."},{text:"Ask for an investigation update and the expected resolution date."},{text:"Check the applicable CBN escalation process if acknowledgment or resolution is overdue. Do not wait to report ongoing fraud."}]} : {}),
        details:[{title:"Make the investigation request specific",text:"Explain whether the issue is a missing credit, failed transfer or deduction. Supply the amount, date and transaction reference only through the verified bank channel. Ask what the bank found, what happens next and its expected resolution date."},{title:"When to consider escalation",text:"Use the reporting guide to check acknowledgment and resolution requirements. Different complaints have different resolution periods; elapsed time alone does not establish eligibility. Report suspected fraud promptly."}] };
    }
    case "account-security": return { ...base, title:/\b(?:clicked|opened|installed|tapped)\b/.test(text) ? "Check your access after the suspicious link or download" : "Protect the account access you are concerned about", summary:"Opening a link is not proof that your device or account was compromised. Treat possible access exposure carefully and use the provider's official service.", details:[{title:"What changes the urgency",text:"If you entered credentials, installed software or noticed unexpected account activity, explain that without sharing the credentials here. If banking access may be affected, contact your bank immediately. PauseAm does not scan your device or detect malware."}] };
    case "impersonation": return { ...base, title:"Verify who is making this request", summary:"The message or caller you described needs an independent identity check. A familiar display name or urgent instruction does not establish who is behind it.", details:[{title:"Use a separate route",text:"Contact the organisation through its official service or a contact you already knew. Do not use the link, phone number or reply address supplied only in the suspicious request. Keep banking secrets private."}] };
    case "payment": return { ...base, title:"Tell us which part of the payment is worrying you", summary:"There is not enough context to choose a specific payment solution. You can clarify without sharing an account number or secret code.", details:[], followUp:{question:"What happened?",choices:[{label:"I have not paid yet",statement:"I have not paid yet and want to verify the payment request."},{label:"I was debited but it did not arrive",statement:"My bank debited the transfer but the recipient has not received it."},{label:"I paid and the seller disappeared",statement:"I paid and the seller disappeared."},{label:"The recipient may be wrong",statement:"I may have sent the transfer to the wrong recipient."}]}};
    default: return null;
  }
}

export function withGuidance(question: string, answer: Answer, now = new Date()): Answer {
  const guidance = contextualGuidance(question, answer, now);
  return guidance ? { ...answer, guidance } : answer;
}
