"""Update local ONDI prose; browser entry and upload remain separate actions."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
path = ROOT / 'submission/ondi-answer-drafts.json'
data = json.loads(path.read_text(encoding='utf-8'))
answers = {
 'Team Member Details': 'Kayode Popoola leads product, payment-safety content, partnerships and user research. He is Head of Sales and Business Development at Secret Network Foundation, a blockchain intelligence and financial crime analyst, and a member of the International Association of Financial Crime Investigators. Suleiman is our Technical lead, responsible for application engineering, N-ATLaS integration, model hosting, deployment and testing.',
 'Why did you choose this problem statement?': 'People receive payment requests through calls and messages but often struggle to verify them or find help after paying. PauseAm turns a spoken question into practical verification and reporting steps. We chose PS2 to make this help accessible through Nigerian-accented English on ordinary phones, without requiring an account or technical knowledge.',
 'Describe the artefact you are building (or have built)': 'PauseAm is a mobile payment decision companion: Ask before you pay. Users speak or type a question, check a payment request, find bank-first help after a suspected scam, or learn a warning sign. Official Nigerian-accented English ASR produces a transcript for correction. The N-ATLaS text model checks which reviewed guidance fits the question. Voice questions receive spoken replies with text and replay/stop controls; typed questions receive text. Guidance includes independent verification steps and official reporting or bank-contact links. Users can preview, copy or download a report draft to send themselves. The current release supports English and handles missing inference or outdated sources with a clear error. It does not move money or authenticate accounts.',
 'PS2: Describe the end-to-end user journey, from voice input to service delivered': 'A user chooses Speak, consents to audio processing and records a question in their own words. They can listen or discard it before transcription. The website sends the recording to our authenticated deployment of NCAIR1/NigerianAccentedEnglish. The transcript appears for correction and confirmation. The pinned NCAIR1/N-ATLaS text model checks the relevance of current, reviewed guidance cards. The app returns practical steps tailored to the payment concern, or asks a short clarifying question. Voice users hear the answer and see its text, with replay and stop controls; typed answers remain silent. Spoken playback uses the device voice. Users can open source details, find verified bank contacts, or build a private report draft for their bank. Urgent after-payment guidance directs them to their bank through an independently verified channel. Unavailable model inference or expired source content produces a clear fallback rather than an improvised answer. Raw audio is not retained by default. The current voice journey is English-only.',
 'PS2: User-acquisition plan for reaching 1,000 users within 3 months of award': 'We will start with our pool of more than 200 willing testers, improve the product from documented feedback, and work with student communities and small-business partners. Our post-award acquisition targets are 200 users in month one, 300 additional users in month two and 500 in month three. These are planned targets. Distribution will use partner demonstrations, voluntary sharing of educational examples and a free first-use journey. We will measure useful completion, comprehension and return use, then expand the channels that work. Additional languages will require compute capacity and fluent review. We will maintain the shared pilot licence guard and obtain separate licensing before exceeding 1,000 active end users in a rolling 30-day period. Optional human recovery-case support is a future revenue route, with a disclosed support fee plus a percentage of funds actually recovered. A legal partner will review the arrangement and handle legal work before that service launches.',
 'Describe exactly how your artefact integrates with N-ATLAS (model, API, ASR, or training pipeline)': 'PauseAm integrates NCAIR1/NigerianAccentedEnglish for audio-to-text and NCAIR1/N-ATLaS for constrained relevance checking against reviewed payment-safety guidance. Both use pinned official model revisions on our authenticated SecretVM host. The website backend forwards consented English audio to the ASR service and verifies the returned model identity. Users correct and confirm the transcript before guidance is requested. The text service runs the official text weights through llama.cpp with Q4_K_M quantization. It accepts an eligible guidance card or abstains; the app presents independently reviewed actions and source links. Request evidence records model revisions, trace references and measured latency. Quantization is not fine-tuning. These are team-hosted model endpoints, not the official N-ATLaS API. We are seeking organiser confirmation of the self-hosted ASR-service qualification. Reply playback uses the device voice.',
 'N-ATLAS API key / access reference (if issued)': 'Approved Hugging Face access; team-hosted NCAIR1/N-ATLaS and NCAIR1/NigerianAccentedEnglish.',
 'How was the artefact tested with real users, real data, or live benchmarks?': 'Thirty people have tested the live English prototype. We are collecting feedback on the journey used, voice or text input, device/network conditions, transcript corrections, completion, useful next steps and errors. We provide fictional payment scenarios for testing. Our observed-session protocol measures the complete voice journey and whether users understand what to do next. Separately, the current release passed 80 application tests and ten public backend checks; four used the pinned N-ATLaS text model.',
 'Key results or feedback from validation': 'Feedback from the 30 testers is being collected and has not yet been analysed. Development testing led to fixes for free-form amount/date questions, combined bank-contact requests and generic guidance. The product supports transcript correction, contextual next steps, voice replay/stop, silent typed answers and report-draft download. Four live N-ATLaS text requests completed in 5,960-7,803 ms. We will use participant feedback to assess completion, comprehension and the most useful improvements.',
 'Who benefits from this build, and how many people could it reach?': 'Nigerian students, everyday users and small businesses benefit when they need to check an unexpected payment request, respond to suspected fraud or find verified bank and complaint information. Voice input offers a practical route for people who find typing difficult or prefer explaining an issue aloud. Our initial post-award target is 1,000 users within three months, reached through student and small-business partnerships. Wider reach will depend on validation, hosting capacity, language review and the required model licensing.',
 'What is your plan to sustain or scale the build beyond the challenge?': 'Keep first-use guidance free and improve PauseAm through user feedback and student/small-business partnerships. Maintain official-source content, monitor model latency and hosting costs, and add languages as compute and fluent-review capacity allow. Obtain separate commercial permission and the required licence before exceeding 1,000 active end users in a rolling 30-day period. Our proposed paid service is optional human recovery-case support: a disclosed support fee plus an agreed percentage of money actually recovered. A Nigerian legal partner is available to review the arrangement and handle legal advice and court work. We will establish written terms and secure case intake before launching this service. Recovery is not guaranteed.',
 'Are you seeking support for this build?': 'Yes. We seek funding and compute credits, official N-ATLaS ASR/API onboarding, deployment and licensing guidance, security and accessibility mentorship, and partnerships for user research and distribution. Legal/IP support will help us structure the proposed recovery-support service.'
}
for field, answer in answers.items():
    item = next((i for i in data['drafts'] if i['field'] == field), None)
    if item is None:
        item = {'field': field, 'verifiedLimit': 1500 if field != 'N-ATLAS API key / access reference (if issued)' else None}
        data['drafts'].append(item)
    item.update(answer=answer, characters=len(answer), withinLimit=len(answer) <= item['verifiedLimit'] if item['verifiedLimit'] else None)
    assert item['withinLimit'] is not False, field
data['scope'] = 'English-scope ONDI draft answers, 3 October 2026. Public evidence and product facts; save without submitting.'
data['selections']['buildStatus'] = 'Working English voice/text prototype; 30 people have tested it and feedback collection is in progress.'
data['selections']['reportedTesters'] = 30
data['selections'].pop('completedInteractions', None)
data['selections']['reviewedCompletedVoiceInteractions'] = 0
data['selections']['portalTestSessions'] = 30
path.write_text(json.dumps(data, indent=2, ensure_ascii=False)+'\n', encoding='utf-8')
print('Updated', len(answers), 'answers; all verified character limits passed.')
