"""Update LOCAL drafts only; never accesses or submits ONDI."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
file=root/'submission/ondi-answer-drafts.json'
data=json.loads(file.read_text(encoding='utf-8'))
answers={
'Team Member Details': "Kayode Popoola leads product, payment-safety content, partnerships and research. His supplied background includes Head of Sales and Business Development at Secret Network Foundation, blockchain intelligence and financial-crime analysis, and IAFCI membership. Suleiman is Technical lead, responsible for implementation, model integration, deployment and testing. These facts await the team's final review.",
'Describe the artefact you are building (or have built)': "PauseAm is a mobile web companion for payment questions, bank-first fraud-report guidance and practical scam lessons. Current scope is English. A real owner recording produced a transcript through the official Nigerian-accented-English weights on our SecretVM; participant accuracy testing remains pending. Typed guidance uses reviewed source checklists. Users review report drafts and send them themselves; PauseAm never moves money, authenticates accounts or promises recovery. A pinned N-ATLaS CPU card-selection service is built but live text inference is not yet proven or enabled. Yoruba, Hausa and Igbo are paused. Source facts and model selections are separate; secrets stay server-side and raw audio is not retained by default. The public app and repository exist; final live integration evidence, 50 genuine documented interactions and the demonstration video remain incomplete.",
'Technology stack / key tools used': "React/TypeScript, Vinext/Vite, Workers/D1; Python/FastAPI, Transformers/PyTorch ASR; pinned N-ATLaS/llama.cpp Q4_K_M CPU candidate.",
'Link to public repository, live demo, or deployed application': "https://github.com/thepopeblack-byte/pauseam | https://pauseam.theblockcapitol.com",
'PS2: Describe the end-to-end user journey, from voice input to service delivered': "Current English flow: choose a payment question; consent to microphone use; record, listen or discard; separately consent to processing; convert to bounded mono 16 kHz WAV; send server-side to the authenticated official-model host; verify exact model identity and privacy; show the transcript for correction and confirmation; return a short reviewed action checklist. A genuine owner transcript is evidenced; this is not participant validation. Typed source guidance works. The N-ATLaS text service is being converted and checked for CPU use; it remains disabled until genuine host relevance and latency checks pass. It selects only an allowed reviewed card, never model-written contacts or arbitrary safety prose. Failures offer an honest retry/text route, without simulated output. Bank-first report guidance appears immediately; a redacted draft stays in the browser for user review and sending. Learning uses dated, manually maintained official notices. No raw audio retention, PINs, OTPs, passwords, full credentials, safe verdicts or recovery promises. Yoruba, Hausa and Igbo are paused. Organiser acceptance of self-hosted official ASR weights remains unresolved; official API and fine-tuning are unverified.",
'PS2: User-acquisition plan for reaching 1,000 users within 3 months of award': "The reported 200+ people are prospective willing testers, not existing users. The owner will coordinate discovery and at least 50 consented, observed English voice interactions after the live build passes. If results support the companion, projected post-award acquisition is 200 completed users in month one, 300 additional users in month two and 500 more in month three through student/small-business partners and voluntary educational sharing. These figures are targets, not traction. Measure completion, comprehension, failures and return use without saving private questions or credentials. Expansion to paused languages requires compute and fluent review. Preserve the conservative shared rolling licence guard and obtain separate licensing before exceeding 1,000 active users in a rolling 30 days. Proposed sustainability is sponsored/B2B distribution and support, with the first consumer action free; willingness-to-pay and pricing remain unvalidated.",
'Working artefact evidence (repository / deployed app link / model / API / dataset)': "https://github.com/thepopeblack-byte/pauseam | https://pauseam.theblockcapitol.com"
}
for draft in data['drafts']:
 if draft['field'] in answers:draft['answer']=answers[draft['field']]
 draft['characters']=len(draft['answer'])
 limit=draft['verifiedLimit']
 draft['withinLimit']=None if limit is None else len(draft['answer'])<=limit
 if draft['withinLimit'] is False:raise SystemExit('Known character limit exceeded: '+draft['field'])
data['scope']='Local current English-scope drafts, 2 October 2026. Actual page 1–2 limits only; unknown limits remain null. No ONDI fields edited or submitted. Reconcile after final model/human evidence.'
data['selections'].update({'completedInteractions':0,'capabilities':[], 'languagesProvenByLiveVoice':['Nigerian-accented English (owner engineering smoke only; participant review pending)'],'buildStatus':'Working English source guidance and owner ASR smoke; CPU text candidate not yet live-proven. No submission capability selection is authorized from these local drafts.'})
file.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print('Local drafts reconciled; all known character limits passed. Unknown limits not asserted.')
